Fix unknown PluginPolicy
It causes the following error such as: error C3646: 'PluginPolicy'

See also:

  Delete cef_web_plugin.h and plugin-related APIs (see issue #3047)

  https://bitbucket.org/chromiumembedded/cef/issues/3047/
  https://bitbucket.org/chromiumembedded/cef/commits/28c7f040016a